#!/usr/bin/env node

/**
* Module dependencies.
*/

var fs = require('fs');
var program = require('commander');
var request = require('request');
var Overpass = require('./lib/overpass')({timeout: 60 * 60 * 1000});

program
.version('0.1.0')
.option('-d, --download', 'Download OpenStreetMap data')
.option('-p, --parse', 'Parse downloaded data.')
.parse(process.argv);

if (program.download) {

  // load query file
  fs.readFile('ufs.overpass', function(err, data){
    if (err) return console.log('Error reading "query.overpass" file.')

    Overpass.get(data, function(err, results){
        if (err) return console.log(err);

        fs.writeFile('./data/osm.json', JSON.stringify(results), function(err){
          if (err) return console.log(err);
          console.log('Download success.');
        })
    });
  });
}

if (program.parse) {


  // var data = require('./data')

}
